spring:
  application:
    name: function-control-producer-server
  cloud:
    nacos:
      config:
        namespace: becf336b-3ccf-4c6b-be93-e51c1542bece
        group: function-control-producer-server
        password: nacos
        enable-remote-sync-config: true
        server-addr: 127.0.0.1:8848
        username: nacos
        name: function-control-producer-server
        file-extension: properties
    stream:
      function:
        definition: source1
      bindings:
        source1-out-0:
          destination: function-topic
      rocketmq:
        binder:
          name-server: 192.168.0.182:9876
          group: function-group
          enabled: true
  config:
    import: "nacos:127.0.0.1:8848"
server:
  port: 8022
