spring:
  application:
    name: product-source-server
  cloud:
    nacos:
      config:
        namespace: becf336b-3ccf-4c6b-be93-e51c1542bece
        group: product-source-server
        password: nacos
        enable-remote-sync-config: true
        server-addr: 127.0.0.1:8848
        username: nacos
        name: product-source-server
        file-extension: properties
      discovery:
        group: rocketmq-practice
        server-addr: 127.0.0.1:8848
        namespace: becf336b-3ccf-4c6b-be93-e51c1542bece
server:
  port: 8026
